### ISSUE TITLE
got errors when running emirge_amplicon.py

### ISSUE THREAD

**Issue by yxxue** [csmiller/EMIRGE#23] opened 2016-04-01 11:27 UTC
Hi,
I installed EMIRGE following the instrcution. The orginal  'emirge.py' seems work well, but the new version 'emrige_amplicon.py' that for large dataset got errors:

_$ ./emirge_amplicon.py
Traceback (most recent call last):
  File "./emirge_amplicon.py", line 61, in <module>
    import _emirge_amplicon as _emirge
  File "build/bdist.linux-x86_64/egg/_emirge_amplicon.py", line 7, in <module>
  File "build/bdist.linux-x86_64/egg/_emirge_amplicon.py", line 6, in __bootstrap__
ImportError: /Home/ii/yaxinx/.python-eggs/EMIRGE-0.60.2a6-py2.7-linux-x86_64.egg-tmp/_emirge_amplicon.so: undefined symbol: gzread_

Anyone know how to fix it? Thanks very much.

**Comment by epruesse** [comment] 2016-04-01 19:30
Hi yxxue,

thank you for reporting this issue! The error you are seeing was caused by a missing setting in setup.py and should be fixed in EMIRGE v0.60.3. Could you try whether the new version works for you?

**Comment by yxxue** [comment] 2016-04-04 09:56
Hi,
I updated the repo and reinstalled, but still meet the same problem.
$ ./emirge_amplicon.py
Traceback (most recent call last):
  File "./emirge_amplicon.py", line 61, in <module>
    import _emirge_amplicon as _emirge
  File "build/bdist.linux-x86_64/egg/_emirge_amplicon.py", line 7, in <module>
  File "build/bdist.linux-x86_64/egg/_emirge_amplicon.py", line 6, in __bootstrap__
ImportError: /Home/ii/yaxinx/.python-eggs/EMIRGE-0.60.3-py2.7-linux-x86_64.egg-tmp/_emirge_amplicon.so: undefined symbol: gzread

Here is the output info when running 'setup.py install', maybe you could help me check. Thanks.

 $ python setup.py install
Found Cython.
running install
running bdist_egg
running egg_info
writing requirements to EMIRGE.egg-info/requires.txt
writing EMIRGE.egg-info/PKG-INFO
writing top-level names to EMIRGE.egg-info/top_level.txt
writing dependency_links to EMIRGE.egg-info/dependency_links.txt
reading manifest file 'EMIRGE.egg-info/SOURCES.txt'
writing manifest file 'EMIRGE.egg-info/SOURCES.txt'
installing library code to build/bdist.linux-x86_64/egg
running install_lib
running build_ext
creating build/bdist.linux-x86_64/egg
copying build/lib.linux-x86_64-2.7/_emirge_amplicon.so -> build/bdist.linux-x86_64/egg
copying build/lib.linux-x86_64-2.7/_emirge.so -> build/bdist.linux-x86_64/egg
copying build/lib.linux-x86_64-2.7/pykseq.so -> build/bdist.linux-x86_64/egg
creating stub loader for pykseq.so
creating stub loader for _emirge.so
creating stub loader for _emirge_amplicon.so
byte-compiling build/bdist.linux-x86_64/egg/pykseq.py to pykseq.pyc
byte-compiling build/bdist.linux-x86_64/egg/_emirge.py to _emirge.pyc
byte-compiling build/bdist.linux-x86_64/egg/_emirge_amplicon.py to _emirge_amplicon.pyc
installing package data to build/bdist.linux-x86_64/egg
running install_data
warning: install_data: setup script did not provide a directory for 'pykseq/kseq.h' -- installing right in 'build/bdist.linux-x86_64/egg'

copying pykseq/kseq.h -> build/bdist.linux-x86_64/egg
warning: install_data: setup script did not provide a directory for '_emirge_C.h' -- installing right in 'build/bdist.linux-x86_64/egg'

copying _emirge_C.h -> build/bdist.linux-x86_64/egg
creating build/bdist.linux-x86_64/egg/EGG-INFO
installing scripts to build/bdist.linux-x86_64/egg/EGG-INFO/scripts
running install_scripts
running build_scripts
creating build/bdist.linux-x86_64/egg/EGG-INFO/scripts
copying build/scripts-2.7/emirge.py -> build/bdist.linux-x86_64/egg/EGG-INFO/scripts
copying build/scripts-2.7/emirge_amplicon.py -> build/bdist.linux-x86_64/egg/EGG-INFO/scripts
copying build/scripts-2.7/emirge_rename_fasta.py -> build/bdist.linux-x86_64/egg/EGG-INFO/scripts
changing mode of build/bdist.linux-x86_64/egg/EGG-INFO/scripts/emirge.py to 755
changing mode of build/bdist.linux-x86_64/egg/EGG-INFO/scripts/emirge_amplicon.py to 755
changing mode of build/bdist.linux-x86_64/egg/EGG-INFO/scripts/emirge_rename_fasta.py to 755
copying EMIRGE.egg-info/PKG-INFO -> build/bdist.linux-x86_64/egg/EGG-INFO
copying EMIRGE.egg-info/SOURCES.txt -> build/bdist.linux-x86_64/egg/EGG-INFO
copying EMIRGE.egg-info/dependency_links.txt -> build/bdist.linux-x86_64/egg/EGG-INFO
copying EMIRGE.egg-info/requires.txt -> build/bdist.linux-x86_64/egg/EGG-INFO
copying EMIRGE.egg-info/top_level.txt -> build/bdist.linux-x86_64/egg/EGG-INFO
writing build/bdist.linux-x86_64/egg/EGG-INFO/native_libs.txt
zip_safe flag not set; analyzing archive contents...
creating 'dist/EMIRGE-0.60.3-py2.7-linux-x86_64.egg' and adding 'build/bdist.linux-x86_64/egg' to it
removing 'build/bdist.linux-x86_64/egg' (and everything under it)
Processing EMIRGE-0.60.3-py2.7-linux-x86_64.egg
Removing /Home/ii/yaxinx/bin/Python-2.7.10/lib/python2.7/site-packages/EMIRGE-0.60.3-py2.7-linux-x86_64.egg
Copying EMIRGE-0.60.3-py2.7-linux-x86_64.egg to /Home/ii/yaxinx/bin/Python-2.7.10/lib/python2.7/site-packages
EMIRGE 0.60.3 is already the active version in easy-install.pth
Installing emirge_amplicon.py script to /Home/ii/yaxinx/bin/Python-2.7.10/bin
Installing emirge.py script to /Home/ii/yaxinx/bin/Python-2.7.10/bin
Installing emirge_rename_fasta.py script to /Home/ii/yaxinx/bin/Python-2.7.10/bin

Installed /Home/ii/yaxinx/bin/Python-2.7.10/lib/python2.7/site-packages/EMIRGE-0.60.3-py2.7-linux-x86_64.egg
Processing dependencies for EMIRGE==0.60.3
Searching for biopython==1.66
Best match: biopython 1.66
Adding biopython 1.66 to easy-install.pth file

Using /Home/ii/yaxinx/bin/Python-2.7.10/lib/python2.7/site-packages
Searching for scipy==0.16.1
Best match: scipy 0.16.1
Adding scipy 0.16.1 to easy-install.pth file

Using /Home/ii/yaxinx/bin/Python-2.7.10/lib/python2.7/site-packages
Searching for pysam==0.9.0
Best match: pysam 0.9.0
Processing pysam-0.9.0-py2.7-linux-x86_64.egg
pysam 0.9.0 is already the active version in easy-install.pth

Using /Home/ii/yaxinx/bin/Python-2.7.10/lib/python2.7/site-packages/pysam-0.9.0-py2.7-linux-x86_64.egg
Searching for numpy==1.10.1
Best match: numpy 1.10.1
Adding numpy 1.10.1 to easy-install.pth file

Using /Home/ii/yaxinx/bin/Python-2.7.10/lib/python2.7/site-packages
Finished processing dependencies for EMIRGE==0.60.3

NOTE:
To download a standard candidate SSU database to use with EMIRGE, run
python emirge_download_candidate_db.py

**Comment by epruesse** [comment] 2016-04-04 19:45
Hi @yxxue,

it looks like the .so files weren't rebuilt. Could you try with a "fresh" directory? 

(That's the easiest way to make sure nothing left from previous builds is causing your issues. You could also remove ```build/```, ```dist/``` and all ```*.so``` and ```*.c``` files. Just make sure that after the "build" the ```_emirge_amplicon.so``` file is actually from today.)

Elmar

**Comment by yxxue** [comment] 2016-04-05 10:54
Hi,
Thanks for your help. After deleting old folder and reinstalling, it works well now.

**Comment by epruesse** [comment] 2016-04-06 16:31
You're welcome :)

**Closed** 2016-04-06 16:31 UTC
